<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HPDA0161" name="com.qait.automation.stik.test.TC_029" tests="11" failures="7" timestamp="26 Feb 2014 05:35:43 GMT" time="102.053" errors="1">
  <testcase name="I_Verify_CompleteProfile_And_UnlockPotential_Sections" time="0.001" classname="com.qait.automation.stik.test.TC_029"/>
  <testcase name="G_Verify_Facebook_Google_Linkedin_Boost_Profile_Section" time="0.000" classname="com.qait.automation.stik.test.TC_029"/>
  <testcase name="E_Verify_LeaderBoard_Section" time="0.001" classname="com.qait.automation.stik.test.TC_029"/>
  <testcase name="F_Verify_Facebook_Google_Linkedin_Share_Profile_Section" time="0.000" classname="com.qait.automation.stik.test.TC_029"/>
  <testcase name="A_launch_URL_Navgiate_to_Stick_HomePage" time="12.597" classname="com.qait.automation.stik.test.TC_029"/>
  <testcase name="C_Verify_Home_Page_Loads_With_All_Sections" time="28.130" classname="com.qait.automation.stik.test.TC_029">
    <error type="java.lang.AssertionError" message="Client Dashboard not present!!! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Client Dashboard not present!!! expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at com.qait.automation.stik.actionfixtures.UserHomePageFixture.verifyHomePageLoads(UserHomePageFixture.java:16)
	at com.qait.automation.stik.test.TC_029.C_Verify_Home_Page_Loads_With_All_Sections(TC_029.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- C_Verify_Home_Page_Loads_With_All_Sections -->
  <testcase name="B_Login_Using_FaceBook_Link_Given_On_Home_Page" time="51.887" classname="com.qait.automation.stik.test.TC_029"/>
  <testcase name="setup" time="9.435" classname="com.qait.automation.stik.test.TC_029"/>
  <testcase name="J_signOut" time="0.000" classname="com.qait.automation.stik.test.TC_029"/>
  <testcase name="H_Verify_LatestReviews_Section" time="0.001" classname="com.qait.automation.stik.test.TC_029"/>
  <testcase name="D_Verify_Client_Panel_Section" time="0.001" classname="com.qait.automation.stik.test.TC_029"/>
</testsuite> <!-- com.qait.automation.stik.test.TC_029 -->
